# Generated by Django 3.0.5 on 2020-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfeature',
            name='position',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MainFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='subtitle')),
                ('image', models.ImageField(upload_to='img/')),
                ('features', models.ManyToManyField(to='app_features.AppFeature', verbose_name='features')),
            ],
        ),
    ]
