# Generated by Django 3.0.5 on 2020-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='store_url')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.CharField(max_length=50, verbose_name='icon')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('links', models.ManyToManyField(to='app_download.DownloadLink', verbose_name='links')),
            ],
        ),
    ]
