# Generated by Django 3.0.5 on 2020-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmission',
            name='image',
            field=models.ImageField(default=None, upload_to='img/'),
            preserve_default=False,
        ),
    ]
