# Generated by Django 3.0.5 on 2020-06-24 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0002_appmission_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appmission',
            old_name='name',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='appmission',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
