# Generated by Django 3.0.5 on 2020-06-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactentry',
            old_name='mesage',
            new_name='message',
        ),
    ]
