# Generated by Django 3.0.5 on 2020-06-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_applanding_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='applanding',
            name='logo',
            field=models.ImageField(default='None', upload_to='img/'),
            preserve_default=False,
        ),
    ]
