# Generated by Django 3.0.5 on 2020-06-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_download', '0001_initial'),
        ('app_header', '0002_auto_20200623_1524'),
        ('home', '0003_applanding_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applanding',
            name='download_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE,
                                       to='app_download.DownloadSection', verbose_name='downloads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applanding',
            name='header',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='app_header.AppDetails', verbose_name='details'),
        ),
    ]
