# Generated by Django 3.0.5 on 2020-06-24 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0003_auto_20200624_1838'),
        ('home', '0005_applanding_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='applanding',
            name='about_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE,
                                       to='app_about.AppMission', verbose_name='mission'),
            preserve_default=False,
        ),
    ]
