# Generated by Django 3.0.5 on 2020-06-25 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
        ('home', '0006_applanding_about_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='applanding',
            name='reviews',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='testimonials.TestimonialsSection', verbose_name='reviews'),
            preserve_default=False,
        ),
    ]
