# Generated by Django 3.0.5 on 2020-06-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_screens', '0001_initial'),
        ('home', '0007_applanding_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='applanding',
            name='screens',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_screens.AppScreens', verbose_name='screens'),
            preserve_default=False,
        ),
    ]
